title: Papirfly Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://timely-marigold-a998a7.netlify.app
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: false
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: true
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Papirfly Web Services
      description: Web applications hosted by Papirfly
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#2b0a5b"
  enableLastMod: true
  headerTextColor: white
  logo: Papirfly_Logo_White_3x.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Papirfly Web hotels
      link: https://timely-marigold-a998a7.netlify.app/pages/papirfly-web-hotels
    - name: Papirfly Global
      link: https://www.papirfly.com
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
